---
title: "O serviço de consultoria"
hidetitle: true
type: "static"
---

<div class = "sobre row">
  
#### A consultoria científica

##### Para quem é o serviço de consultoria científica?
Esse serviço é para:  

* Você, que ainda não coletou os seus dados e gostaria de conversar sobre o delineamento do seu experimento e sobre essa coleta  

* Você, que já coletou os seus dados e quer discutir quais análises são adequadas a eles e como fazê-las/ reportá-las  

* Você, que quer contratar um serviço de análise de dados, mas está com dificuldade em definir suas perguntas experimentais e variáveis de interesse  
  
<br>
Se você gosta da forma como eu explico os conteúdos no YouTube, provavelmente vai gostar da consultoria.

##### O que inclui o serviço de consultoria?
A consultoria é realizada **online** (via Google Meet) e será estruturada de acordo com a sua necessidade.  
Por exemplo, caso a sua demanda seja rodarmos as suas análises, vou te pedir para me enviar seus dados/ script com antecedência. Na reunião online, faremos as análises - que eu já terei rodado antes, ao montar a consultoria - e discutiremos seus resultados, soluções de possíveis problemas, e como descrevê-los no seu trabalho.  
Uma hora consultoria rende muito, porque eu já chego no nosso encontro ao vivo com tudo bem estruturado. Para a maior parte dos alunos, uma ou duas horas são suficientes.
Ah, para a parte de análise ao vivo, **as opções de programa estatístico são R, JASP e Jamovi**, ok?

##### Quanto custa esse serviço?
O valor da hora de consultoria é **R$ 250**.  
O pagamento desse valor pode ser realizado via Pix ou boleto bancário.

##### Para quando eu consigo agendar a consultoria?
A consultoria será agendada de acordo com a nossa disponibilidade (minha e sua). Então, não deixe para a última hora, porque pode levar mais de uma semana para conseguirmos uma data adequada.
Ah, **vamos conversar por e-mail antes de fecharmos uma data**, porque eu preciso entender a sua demanda para conseguir estruturar a consultoria e também para avaliar se o tema está dentro da minha área de conhecimento.  
  
<br>

<center>
<a href="https://forms.gle/1eAjTtdprsBMtwGo6" class="button" target="_blank">
QUERO AGENDAR UMA CONSULTORIA
</a>
</center>

<br>

</div>

