---
title: "O serviço de análise de dados"
hidetitle: true
type: "static"
---

<div class = "sobre row">
  
#### A análise de dados

##### Para quem é o serviço de análise de dados?
Para você que já coletou os seus dados e quer contratar uma especialista para realizar a etapa de análise.  

##### O que está incluído neste serviço?
Ao contratar a análise, você me envia o seu banco, eu defino as análises mais adequadas aos seus dados e à sua pergunta experimental e realizo essas análises. Ao final, te entrego um relatório completo: com descrição detalhada da metodologia, dos resultados (descritos em textos, gráficos e tabelas) e com toda a bibliografia utilizada.  
<br>
Depois da entrega do relatório, temos uma reunião de devolutiva (online, via Google Meet), para que você possa tirar todas as suas dúvidas.  
<br>
Nesse serviço, as análises são realizadas exclusivamente no software <a href="https://www.r-project.org/" target="_blank">R</a>.  

##### Quanto custa esse serviço?
O custo depende da extensão e complexidade da análise de dados.  
Por isso, para te passar um orçamento, eu preciso de uma descrição detalhada: da sua pergunta experimental, de quais dados você coletou e de como está o seu banco de dados.  
**Todo o processo de orçamento e planejamento das análises é feito por e-mail**.  
  
<br>

<center>
<a href="https://forms.gle/FaYCjcVZpToX7Wo5A" class="button" target="_blank">
QUERO UM ORÇAMENTO PARA ANÁLISE DE DADOS
</a>
</center>

<br>
  
##### Quem fará as análises?
Todas as análises serão feitas por mim, Fernanda. Sou bacharel em biomedicina, especialista em estatística aplicada e mestre e doutora em ciências ([acesso ao currículo completo](http://lattes.cnpq.br/7696717599003359)). Sou também orientadora de cursos de graduação e especialização.  
<br>
Um diferencial do serviço é que ele será realizado por alguém com experiência na redação de TCC, dissertação, tese e artigos científicos. O relatório que você recebe na consultoria é redigido em uma linguagem adequada a esse tipo de documento e inclui todas as informações necessárias.  
  
##### Qual o prazo para entrega do relatório completo com a análise?
Assim como o orçamento, o prazo de entrega vai **depender da complexidade da sua análise**.  
Mas, a maior parte dos relatórios são entregues dentro de 15 dias.  
Não deixe para a última hora. O momento ideal de contratar o serviço de consultoria é uns bons meses antes da sua qualificação/ defesa.  
  

</div>
