---
title: "Serviços"
hidetitle: true
type: "static"
---

<div class = "sobre row">
  
<center>Oi! Tudo bem?

Eu ofereço dois tipos de serviço: o de **consultoria científica** e o de **aula particular/ mentoria**.

Como eles funcionam?</center>


<div class = "column3">

#### Consultoria científica

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<br>

<ul>

<li>
<p>2016 - 2021</p>
<p>Doutorado em Farmacologia</p>
<p><i>Universidade Federal de São Paulo (UNIFESP)</i></p>
</li>

<li>
<p>2018 - 2020</p>
<p>Especialização em estatística aplicada</p>
<p><i>Universidade Cruzeiro do Sul</i></p>
</li>

<li>
<p>2013 - 2015</p>
<p>Mestrado em Farmacologia</p>
<p><i>Universidade Federal de São Paulo (UNIFESP)</i></p>
</li>

<li>
<p>2009 - 2012</p>
<p>Graduação em Ciências Biológicas - Modalidade Médica</p>
<p><i>Universidade Federal de São Paulo (UNIFESP)</i></p>
</li>

</ul>

<br><br>

<center>
<a href="http://lattes.cnpq.br/7696717599003359" class="button">Currículo Completo (Lattes)</a>
</center>

</div>


<div class = "column4">

#### Histórico Profissional

<br>

<ul>

<li class = "g">
<p>2018 - atual</p>
<p>Consultorias científicas e aulas particulares de bioestatística</p>
</li>

<li class = "t">
<p>2021 - atual</p>
<p>Professora dos Cursos de Data Science e Data Analytics</p>
<p><i>Tera</i></p>
</li>

<li class = "t">
<p>2019 - atual</p>
<p>Professora de Psicofarmacologia do curso de Especialização em Neurociências</p>
<p><i>Universidade Federal de São Paulo (UNIFESP)</i></p>
</li>

<li class = "t">
<p>2016 - atual</p>
<p>Professora dos cursos técnico em Farmácia e graduação em Biomedicina</p>
<p><i>Faculdade Método de São Paulo (Famesp)</i></p>
</li>

<li class = "t">
<p>2022</p>
<p>Professora de Bioestatística do curso de Especialização em Fisiopatologia</p>
<p><i>Universidade Federal de São Paulo (UNIFESP)</i></p>
</li>

<li class = "t">
<p>2020</p>
<p>Professora do curso de graduação em Biomedicina</p>
<p><i>Universidade Paulista (UNIP)</i></p>
</li>


<li class = "t">
<p>2019</p>
<p>Professora de Bioestatística do Programa de Pós Graduação do Departamento de Diagnóstico por Imagem</p>
<p><i>Universidade Federal de São Paulo (UNIFESP)</i></p>
</li>

<li class = "t">
<p>2011 - 2016</p>
<p>Professora e coordenadora da disciplina de Matemática</p>
<p><i>Cursinho Universitário Jeannine Aboulafia (CUJA)</i></p>
<p><i>Projeto de Extensão da Universidade Federal de São Paulo (UNIFESP)</i></p>
</li>

</ul>
  
</div>

</div>

